# Exploração e Qualidade dos Dados

Este notebook tem como objetivo explorar os dados armazenados nos bancos de dados
**SQL Server** e **PostgreSQL** utilizando Python e Pandas, de forma **comparativa**.

Como o PostgreSQL foi gerado a partir de um processo de ETL a partir do SQL Server,
o objetivo aqui não é só entender os dados, mas também **identificar divergências**
entre os dois bancos que possam ter surgido durante essa migração.

As análises serão direcionadas para:

- Conhecer a estrutura das tabelas em ambos os bancos;
- Identificar quantidade de registros e colunas;
- Verificar tipos de dados;
- Analisar valores nulos;
- Identificar registros duplicados;
- Verificar possíveis chaves primárias;
- Realizar agrupamentos e estatísticas;
- Avaliar aspectos relacionados à qualidade dos dados;
- Criar visualizações para auxiliar na interpretação dos dados;
- **Comparar SQL Server e PostgreSQL lado a lado para localizar inconsistências.**

## 1. Conexão com os bancos de dados

As conexões com o SQL Server e o PostgreSQL estão centralizadas no módulo
`src/database/connection.py`, que usa o padrão Strategy para lidar com os dois
bancos de forma intercambiável.

Dessa forma, o notebook não precisa criar nenhuma conexão manualmente.
Apenas importamos os objetos `sqlserver_connection` e `postgres_connection`
já configurados pelo módulo de conexão.

In [3]:
import os
import sys

# Adiciona a raiz do projeto ao caminho de importação do Python.
# O notebook está dentro de tests/notebooks/, portanto precisamos
# subir dois níveis para chegar à raiz do projeto.
raiz_projeto = os.path.abspath("../..")

sys.path.insert(0, raiz_projeto)

In [4]:
# Importa as duas conexões já configuradas no projeto.
from src.database.connection import sqlserver_connection, postgres_connection

print("Conexões carregadas com sucesso!")
print("SQL Server:", sqlserver_connection.engine)
print("PostgreSQL:", postgres_connection.engine)

Conexões carregadas com sucesso!
SQL Server: Engine(mssql+pyodbc://sa:***@localhost:1433/curso_integridade_fiscal?TrustServerCertificate=yes&driver=ODBC+Driver+18+for+SQL+Server)
PostgreSQL: Engine(postgresql+psycopg2://postgres:***@127.0.0.1:5432/postgres)

## 2. Carregamento dos dados

Nesta etapa, a mesma tabela será carregada tanto do SQL Server quanto do
PostgreSQL, cada uma em seu próprio DataFrame do Pandas.

Os dois DataFrames serão utilizados ao longo do notebook para realizar as
mesmas análises exploratórias em paralelo, além de comparações diretas entre
os dois bancos.

In [5]:
import pandas as pd

# Consulta SQL utilizada para carregar os dados.
# Mesma consulta nos dois bancos, para garantir uma comparação justa.
query = """
SELECT *
FROM efd_c170
"""

# Executa a consulta em cada banco e transforma o resultado em um DataFrame.
df_sqlserver = pd.read_sql(query, sqlserver_connection.engine)
df_postgres = pd.read_sql(query, postgres_connection.engine)

print("SQL Server -> registros:", len(df_sqlserver), "| colunas:", len(df_sqlserver.columns))
print("PostgreSQL -> registros:", len(df_postgres), "| colunas:", len(df_postgres.columns))

SQL Server -> registros: 23158 | colunas: 12
PostgreSQL -> registros: 23152 | colunas: 12

## 3. Visualização inicial dos dados

Primeiramente, serão observados alguns registros de cada banco para
compreender como os dados estão estruturados e identificar diferenças visuais
óbvias (nomes de colunas, formatos, valores).

In [6]:
# Cinco primeiros registros de cada banco.
print("SQL Server:")
display(df_sqlserver.head())

print("PostgreSQL:")
display(df_postgres.head())

SQL Server:

,id_c170,id_c100,num_item,cod_item,descricao_complementar,ncm,cfop,cst_icms,quantidade,valor_item,aliquota_icms,valor_icms_item
0,1,1,1,PRD-37477,NaN,22030000,5102,000,5.0,18.48,18.0,3.33
1,2,1,2,PRD-29520,AGUARDENTE DE CANA 1L,22084000,5405,000,200.0,2693.76,20.0,538.75
2,3,1,3,PRD-82388,NaN,22011000,5102,000,2.0,4.14,20.0,0.83
3,4,1,4,PRD-82388,AGUA MINERAL SEM GAS 500ML,22011000,5102,000,6.0,13.87,20.0,2.77
4,5,1,5,PRD-82388,NaN,22011000,5102,000,20.0,31.19,20.0,6.24

PostgreSQL:

,id_c170,id_c100,num_item,cod_item,descricao_complementar,ncm,cfop,cst_icms,quantidade,valor_item,aliquota_icms,valor_icms_item
0,1,1,1,PRD-37477,NaN,22030000,5102,000,5.0,18.48,17.0,3.30
1,2,1,2,PRD-29520,AGUARDENTE DE CANA 1L,22084000,5405,000,200.0,2693.76,20.0,538.75
2,3,1,3,PRD-82388,NaN,22011000,5102,000,2.0,4.14,20.0,0.83
3,4,1,4,PRD-82388,AGUA MINERAL SEM GAS 500ML,22011000,5102,000,6.0,13.87,20.0,2.77
4,5,1,5,PRD-82388,NaN,22011000,5102,000,20.0,31.19,20.0,6.24

In [7]:
# Cinco últimos registros de cada banco.
print("SQL Server:")
display(df_sqlserver.tail())

print("PostgreSQL:")
display(df_postgres.tail())

SQL Server:

,id_c170,id_c100,num_item,cod_item,descricao_complementar,ncm,cfop,cst_icms,quantidade,valor_item,aliquota_icms,valor_icms_item
23153,23154,8030,1,PRD-99999,NaN,84212300,1102,000,4.0,48816.86,18.0,8787.03
23154,23155,8031,1,PRD-99999,NaN,22042100,1102,000,9.0,35639.83,18.0,6415.17
23155,23156,8032,1,PRD-99999,NaN,21069029,1102,000,31.0,48055.29,18.0,8649.95
23156,23157,8033,1,PRD-99999,NaN,84212300,1102,000,34.0,59060.59,18.0,10630.91
23157,23158,8034,1,PRD-99999,NaN,10063021,1102,000,35.0,64541.57,18.0,11617.48

PostgreSQL:

,id_c170,id_c100,num_item,cod_item,descricao_complementar,ncm,cfop,cst_icms,quantidade,valor_item,aliquota_icms,valor_icms_item
23147,23154,8030,1,PRD-99999,NaN,84212300,1102,000,4.0,48816.86,18.0,8787.03
23148,23155,8031,1,PRD-99999,NaN,22042100,1102,000,9.0,35639.83,18.0,6415.17
23149,23156,8032,1,PRD-99999,NaN,21069029,1102,000,31.0,48055.29,18.0,8649.95
23150,23157,8033,1,PRD-99999,NaN,84212300,1102,000,34.0,59060.59,18.0,10630.91
23151,23158,8034,1,PRD-99999,NaN,10063021,1102,000,35.0,64541.57,18.0,11617.48

## 4. Estrutura dos dados

Nesta etapa serão analisados, para os dois bancos:

- quantidade de registros;
- quantidade de colunas;
- nomes das colunas (e se batem entre os dois bancos);
- tipos de dados;
- quantidade de valores preenchidos.

Essas informações ajudam a compreender a estrutura das tabelas e a identificar
diferenças estruturais já nesta fase inicial.

In [8]:
# Dimensões dos DataFrames: (linhas, colunas).
print("SQL Server:", df_sqlserver.shape)
print("PostgreSQL:", df_postgres.shape)

if df_sqlserver.shape[0] != df_postgres.shape[0]:
    print("Divergência na quantidade de registros entre os bancos!")
if df_sqlserver.shape[1] != df_postgres.shape[1]:
    print("Divergência na quantidade de colunas entre os bancos!")

SQL Server: (23158, 12)
PostgreSQL: (23152, 12)
Divergência na quantidade de registros entre os bancos!

In [9]:
# Compara os nomes das colunas entre os dois bancos.
colunas_sqlserver = set(df_sqlserver.columns)
colunas_postgres = set(df_postgres.columns)

apenas_no_sqlserver = colunas_sqlserver - colunas_postgres
apenas_no_postgres = colunas_postgres - colunas_sqlserver

print("Colunas apenas no SQL Server:", apenas_no_sqlserver or "nenhuma")
print("Colunas apenas no PostgreSQL:", apenas_no_postgres or "nenhuma")

Colunas apenas no SQL Server: nenhuma
Colunas apenas no PostgreSQL: nenhuma

In [10]:
# Tipos de dados e quantidade de valores não nulos em cada banco.
print("SQL Server:")
df_sqlserver.info()

print("\nPostgreSQL:")
df_postgres.info()

SQL Server:
<class 'pandas.DataFrame'>
RangeIndex: 23158 entries, 0 to 23157
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_c170                 23158 non-null  int64
 1   id_c100                 23158 non-null  int64
 2   num_item                23158 non-null  int64
 3   cod_item                23158 non-null  str
 4   descricao_complementar  6097 non-null   str
 5   ncm                     23158 non-null  str
 6   cfop                    23158 non-null  str
 7   cst_icms                23158 non-null  str
 8   quantidade              23158 non-null  float64
 9   valor_item              23158 non-null  float64
 10  aliquota_icms           20045 non-null  float64
 11  valor_icms_item         23158 non-null  float64
dtypes: float64(4), int64(3), str(5)
memory usage: 2.1 MB

PostgreSQL:
<class 'pandas.DataFrame'>
RangeIndex: 23152 entries, 0 to 23151
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_c170                 23152 non-null  int64
 1   id_c100                 23152 non-null  int64
 2   num_item                23152 non-null  int64
 3   cod_item                23152 non-null  str
 4   descricao_complementar  6095 non-null   str
 5   ncm                     23152 non-null  str
 6   cfop                    23152 non-null  str
 7   cst_icms                23152 non-null  str
 8   quantidade              23152 non-null  float64
 9   valor_item              23152 non-null  float64
 10  aliquota_icms           20041 non-null  float64
 11  valor_icms_item         23152 non-null  float64
dtypes: float64(4), int64(3), str(5)
memory usage: 2.1 MB

## 5. Análise de valores nulos

Valores nulos podem representar ausência de informação e, dependendo
da coluna, podem comprometer análises ou indicar problemas de qualidade.

Nesta etapa será verificada a quantidade de valores nulos em cada coluna,
para os dois bancos, e destacadas as colunas em que essa quantidade diverge.

In [11]:
# Quantidade de valores nulos por coluna em cada banco.
nulos_sqlserver = df_sqlserver.isnull().sum()
nulos_postgres = df_postgres.isnull().sum()

comparacao_nulos = pd.DataFrame({
    "nulos_sqlserver": nulos_sqlserver,
    "nulos_postgres": nulos_postgres,
})
comparacao_nulos["diferenca"] = (
    comparacao_nulos["nulos_sqlserver"] - comparacao_nulos["nulos_postgres"]
)

comparacao_nulos

                        nulos_sqlserver  nulos_postgres  diferenca
id_c170                               0               0          0
id_c100                               0               0          0
num_item                              0               0          0
cod_item                              0               0          0
descricao_complementar            17061           17057          4
ncm                                   0               0          0
cfop                                  0               0          0
cst_icms                              0               0          0
quantidade                            0               0          0
valor_item                            0               0          0
aliquota_icms                      3113            3111          2
valor_icms_item                       0               0          0

## 6. Análise da chave primária

A chave primária deve identificar unicamente cada registro da tabela, nos
dois bancos.

Nesta análise serão verificadas três características, em cada banco:

1. Existência de valores nulos;
2. Quantidade de valores únicos;
3. Existência de duplicidades.

A coluna analisada deverá ser definida de acordo com a estrutura
da tabela no banco de dados.

In [12]:
coluna_pk = "id_c170"

for nome, df in [("SQL Server", df_sqlserver), ("PostgreSQL", df_postgres)]:
    print(f"--- {nome} ---")
    print("Quantidade de registros:", len(df))
    print("Quantidade de valores únicos:", df[coluna_pk].nunique())
    print("Quantidade de valores nulos:", df[coluna_pk].isnull().sum())
    print("A coluna possui apenas valores únicos:", df[coluna_pk].is_unique)
    print()

--- SQL Server ---
Quantidade de registros: 23158
Quantidade de valores únicos: 23158
Quantidade de valores nulos: 0
A coluna possui apenas valores únicos: True

--- PostgreSQL ---
Quantidade de registros: 23152
Quantidade de valores únicos: 23152
Quantidade de valores nulos: 0
A coluna possui apenas valores únicos: True

In [13]:
# Verifica se a coluna atende aos critérios básicos de unicidade e não nulidade,
# em cada banco.
for nome, df in [("SQL Server", df_sqlserver), ("PostgreSQL", df_postgres)]:
    if df[coluna_pk].is_unique and df[coluna_pk].notna().all():
        print(f"{nome}: a coluna atende aos critérios básicos de unicidade e não nulidade.")
    else:
        print(f"{nome}: foram identificados possíveis problemas na chave.")

SQL Server: a coluna atende aos critérios básicos de unicidade e não nulidade.
PostgreSQL: a coluna atende aos critérios básicos de unicidade e não nulidade.

## 7. Análise de duplicidades

Registros duplicados podem indicar problemas na carga ou na integridade
dos dados, em qualquer um dos bancos.

Primeiramente será verificada a existência de linhas completamente
duplicadas em cada banco.

In [14]:
# Quantidade de linhas completamente duplicadas em cada banco.
duplicados_sqlserver = df_sqlserver.duplicated().sum()
duplicados_postgres = df_postgres.duplicated().sum()

print("Registros duplicados no SQL Server:", duplicados_sqlserver)
print("Registros duplicados no PostgreSQL:", duplicados_postgres)

Registros duplicados no SQL Server: 0
Registros duplicados no PostgreSQL: 0

In [15]:
# Exibe os registros duplicados de cada banco.
print("SQL Server:")
display(df_sqlserver[df_sqlserver.duplicated(keep=False)])

print("PostgreSQL:")
display(df_postgres[df_postgres.duplicated(keep=False)])

SQL Server:

Empty DataFrame
Columns: [id_c170, id_c100, num_item, cod_item, descricao_complementar, ncm, cfop, cst_icms, quantidade, valor_item, aliquota_icms, valor_icms_item]
Index: []

PostgreSQL:

Empty DataFrame
Columns: [id_c170, id_c100, num_item, cod_item, descricao_complementar, ncm, cfop, cst_icms, quantidade, valor_item, aliquota_icms, valor_icms_item]
Index: []

## 8. Comparação direta entre SQL Server e PostgreSQL

Até aqui, cada banco foi analisado separadamente. Nesta seção, os dois
DataFrames são cruzados diretamente pela chave primária para localizar:

- registros presentes em apenas um dos bancos (linhas faltantes/sobrando);
- registros com a mesma chave, mas valores diferentes em alguma coluna;
- divergências em somas e agrupamentos entre os dois bancos.

In [16]:
# Registros presentes em apenas um dos bancos, com base na chave primária.
ids_sqlserver = set(df_sqlserver[coluna_pk])
ids_postgres = set(df_postgres[coluna_pk])

apenas_no_sqlserver_ids = ids_sqlserver - ids_postgres
apenas_no_postgres_ids = ids_postgres - ids_sqlserver

print("Registros presentes apenas no SQL Server:", len(apenas_no_sqlserver_ids))
print("Registros presentes apenas no PostgreSQL:", len(apenas_no_postgres_ids))

# Amostra dos registros "perdidos" na migração, se houver.
if apenas_no_sqlserver_ids:
    display(df_sqlserver[df_sqlserver[coluna_pk].isin(apenas_no_sqlserver_ids)].head())
if apenas_no_postgres_ids:
    display(df_postgres[df_postgres[coluna_pk].isin(apenas_no_postgres_ids)].head())

Registros presentes apenas no SQL Server: 6
Registros presentes apenas no PostgreSQL: 0

,id_c170,id_c100,num_item,cod_item,descricao_complementar,ncm,cfop,cst_icms,quantidade,valor_item,aliquota_icms,valor_icms_item
9,10,3,1,PRD-82388,AGUA MINERAL SEM GAS 500ML,22011000,5102,000,10.0,22.81,25.0,5.70
1999,2000,664,6,PRD-82388,NaN,22011000,5405,040,24.0,45.74,NaN,0.00
5999,6000,2081,1,PRD-55698,NaN,39172390,5102,000,10.0,849.50,18.0,152.91
9999,10000,3460,2,PRD-28329,NaN,25232910,1102,000,6.0,174.09,25.0,43.52
14999,15000,5206,2,PRD-58579,MESA DE MADEIRA 6 LUGARES,94036000,6101,000,5.0,4065.61,12.0,487.87

In [17]:
# Para os registros presentes nos dois bancos, compara valor a valor,
# coluna a coluna, para localizar divergências de dados.
colunas_comuns = [c for c in df_sqlserver.columns if c in df_postgres.columns]

comparacao = df_sqlserver[colunas_comuns].merge(
    df_postgres[colunas_comuns],
    on=coluna_pk,
    how="inner",
    suffixes=("_sqlserver", "_postgres"),
)

def e_diferente(col_a, col_b):
    """Compara duas colunas tratando NaN == NaN como igual (não como divergência)."""
    ambos_nulos = col_a.isna() & col_b.isna()
    return (col_a != col_b) & ~ambos_nulos

divergencias_por_coluna = []
for coluna in colunas_comuns:
    if coluna == coluna_pk:
        continue
    col_sqlserver = f"{coluna}_sqlserver"
    col_postgres = f"{coluna}_postgres"

    mascara_diferentes = e_diferente(comparacao[col_sqlserver], comparacao[col_postgres])
    diferentes = comparacao[mascara_diferentes]

    if len(diferentes) > 0:
        divergencias_por_coluna.append({
            "coluna": coluna,
            "qtd_divergencias": len(diferentes),
        })

resumo_divergencias = pd.DataFrame(divergencias_por_coluna)
resumo_divergencias

            coluna  qtd_divergencias
0    aliquota_icms                 1
1  valor_icms_item                 1

In [19]:
# Mostra alguns exemplos concretos de linhas divergentes, para a primeira
# coluna com divergência encontrada acima (ajuste o nome conforme necessário).
if not resumo_divergencias.empty:
    coluna_exemplo = resumo_divergencias.iloc[0]["coluna"]
    col_sqlserver = f"{coluna_exemplo}_sqlserver"
    col_postgres = f"{coluna_exemplo}_postgres"

    mascara_diferentes = e_diferente(comparacao[col_sqlserver], comparacao[col_postgres])
    exemplos = comparacao[mascara_diferentes]
    display(exemplos[[coluna_pk, col_sqlserver, col_postgres]].head(10))
else:
    print("Nenhuma divergência de valores encontrada nas colunas em comum.")

   id_c170  aliquota_icms_sqlserver  aliquota_icms_postgres
0        1                     18.0                    17.0

## 9. Comparação de agregações

Além da comparação linha a linha, é importante verificar se somas e
contagens agregadas batem entre os dois bancos — divergências aqui podem
indicar problemas sutis (ex: arredondamento, truncamento, conversão de tipo)
que não aparecem claramente na comparação célula a célula.

In [ ]:
# Compara a soma de todas as colunas numéricas entre os dois bancos.
colunas_numericas = df_sqlserver.select_dtypes(include="number").columns.tolist()

resumo_somas = pd.DataFrame({
    "soma_sqlserver": df_sqlserver[colunas_numericas].sum(),
    "soma_postgres": df_postgres[colunas_numericas].sum(),
})
resumo_somas["diferenca"] = resumo_somas["soma_sqlserver"] - resumo_somas["soma_postgres"]

resumo_somas

                 soma_sqlserver  soma_postgres  diferenca
id_c170            2.681581e+08   2.681051e+08   53010.00
id_c100            9.289448e+07   9.287611e+07   18370.00
num_item           5.492300e+04   5.491000e+04      13.00
quantidade         9.653200e+05   9.651450e+05     175.00
valor_item         7.854064e+07   7.853524e+07    5396.96
aliquota_icms      3.689847e+05   3.689037e+05      81.00
valor_icms_item    1.257304e+07   1.257235e+07     690.03