# Exploração e Qualidade dos Dados

Este notebook tem como objetivo explorar os dados armazenados no banco de dados
SQL Server utilizando Python e Pandas.

As análises serão direcionadas para:

- Conhecer a estrutura das tabelas;
- Identificar quantidade de registros e colunas;
- Verificar tipos de dados;
- Analisar valores nulos;
- Identificar registros duplicados;
- Verificar possíveis chaves primárias;
- Realizar agrupamentos e estatísticas;
- Avaliar aspectos relacionados à qualidade dos dados;
- Criar visualizações para auxiliar na interpretação dos dados.

## 1. Conexão com o banco de dados

A conexão com o SQL Server está centralizada no módulo
`src/database/connection.py`.

Dessa forma, o notebook não precisa criar uma nova conexão.
Apenas importamos o objeto `engine` criado pelo módulo de conexão.

In [33]:
import os
import sys

# Adiciona a raiz do projeto ao caminho de importação do Python.
# O notebook está dentro de tests/notebooks/, portanto precisamos
# subir dois níveis para chegar à raiz do projeto.
raiz_projeto = os.path.abspath("../..")

sys.path.insert(0, raiz_projeto)

In [34]:
# Importa a conexão já configurada no projeto.
from src.database.connection import engine

print("Conexão carregada com sucesso!")
print(engine)

Conexão carregada com sucesso!
Engine(mssql+pyodbc://projeto_python:***@localhost:1433/curso_integridade_fiscal?TrustServerCertificate=yes&driver=ODBC+Driver+18+for+SQL+Server)

## 2. Carregamento dos dados

Nesta etapa, uma tabela do SQL Server será carregada para um
DataFrame do Pandas.

O DataFrame será utilizado para realizar as análises exploratórias
e os testes de qualidade dos dados.

In [42]:
import pandas as pd

# Consulta SQL utilizada para carregar os dados.
query = """
SELECT *
FROM efd_c170
"""

# Executa a consulta e transforma o resultado em um DataFrame.
df = pd.read_sql(query, engine)

print(f"Quantidade de registros: {len(df)}")
print(f"Quantidade de colunas: {len(df.columns)}")

Quantidade de registros: 23158
Quantidade de colunas: 12

## 3. Visualização inicial dos dados

Primeiramente, serão observados alguns registros da tabela para
compreender como os dados estão estruturados.

In [43]:
# Exibe os cinco primeiros registros.
df.head()

,id_c170,id_c100,num_item,cod_item,descricao_complementar,ncm,cfop,cst_icms,quantidade,valor_item,aliquota_icms,valor_icms_item
0,1,1,1,PRD-37477,None,22030000,5102,000,5.0,18.48,18.0,3.33
1,2,1,2,PRD-29520,AGUARDENTE DE CANA 1L,22084000,5405,000,200.0,2693.76,20.0,538.75
2,3,1,3,PRD-82388,None,22011000,5102,000,2.0,4.14,20.0,0.83
3,4,1,4,PRD-82388,AGUA MINERAL SEM GAS 500ML,22011000,5102,000,6.0,13.87,20.0,2.77
4,5,1,5,PRD-82388,None,22011000,5102,000,20.0,31.19,20.0,6.24

In [44]:
# Exibe os cinco últimos registros.
df.tail()

,id_c170,id_c100,num_item,cod_item,descricao_complementar,ncm,cfop,cst_icms,quantidade,valor_item,aliquota_icms,valor_icms_item
23153,23154,8030,1,PRD-99999,None,84212300,1102,000,4.0,48816.86,18.0,8787.03
23154,23155,8031,1,PRD-99999,None,22042100,1102,000,9.0,35639.83,18.0,6415.17
23155,23156,8032,1,PRD-99999,None,21069029,1102,000,31.0,48055.29,18.0,8649.95
23156,23157,8033,1,PRD-99999,None,84212300,1102,000,34.0,59060.59,18.0,10630.91
23157,23158,8034,1,PRD-99999,None,10063021,1102,000,35.0,64541.57,18.0,11617.48

## 4. Estrutura dos dados

Nesta etapa serão analisados:

- quantidade de registros;
- quantidade de colunas;
- nomes das colunas;
- tipos de dados;
- quantidade de valores preenchidos.

Essas informações ajudam a compreender a estrutura da tabela
antes de iniciar análises mais específicas.

In [45]:
# Dimensões do DataFrame: (linhas, colunas)
df.shape

(23158, 12)

In [46]:
# Lista de colunas existentes na tabela.
df.columns.tolist()

['id_c170',
 'id_c100',
 'num_item',
 'cod_item',
 'descricao_complementar',
 'ncm',
 'cfop',
 'cst_icms',
 'quantidade',
 'valor_item',
 'aliquota_icms',
 'valor_icms_item']

In [47]:
# Tipos de dados e quantidade de valores não nulos.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23158 entries, 0 to 23157
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_c170                 23158 non-null  int64
 1   id_c100                 23158 non-null  int64
 2   num_item                23158 non-null  int64
 3   cod_item                23158 non-null  object
 4   descricao_complementar  6097 non-null   object
 5   ncm                     23158 non-null  object
 6   cfop                    23158 non-null  object
 7   cst_icms                23158 non-null  object
 8   quantidade              23158 non-null  float64
 9   valor_item              23158 non-null  float64
 10  aliquota_icms           20045 non-null  float64
 11  valor_icms_item         23158 non-null  float64
dtypes: float64(4), int64(3), object(5)
memory usage: 2.1+ MB

## 5. Análise de valores nulos

Valores nulos podem representar ausência de informação e, dependendo
da coluna, podem comprometer análises ou indicar problemas de qualidade.

Nesta etapa será verificada a quantidade de valores nulos em cada coluna.

In [50]:
# Quantidade de valores nulos por coluna.
nulos = df.isnull().sum()

nulos

id_c170                       0
id_c100                       0
num_item                      0
cod_item                      0
descricao_complementar    17061
ncm                           0
cfop                          0
cst_icms                      0
quantidade                    0
valor_item                    0
aliquota_icms              3113
valor_icms_item               0
dtype: int64

## 6. Análise da chave primária

A chave primária deve identificar unicamente cada registro da tabela.

Nesta análise serão verificadas três características:

1. Existência de valores nulos;
2. Quantidade de valores únicos;
3. Existência de duplicidades.

A coluna analisada deverá ser definida de acordo com a estrutura
da tabela no banco de dados.

In [52]:

coluna_pk = "id_c170"

print("Quantidade de registros:", len(df))
print("Quantidade de valores únicos:", df[coluna_pk].nunique())
print("Quantidade de valores nulos:", df[coluna_pk].isnull().sum())
print("A coluna possui apenas valores únicos:", df[coluna_pk].is_unique)

Quantidade de registros: 23158
Quantidade de valores únicos: 23158
Quantidade de valores nulos: 0
A coluna possui apenas valores únicos: True

In [ ]:
# Verifica se a coluna atende aos critérios básicos de unicidade e não nulidade.

if df[coluna_pk].is_unique and df[coluna_pk].notna().all():
    print(" A coluna atende aos critérios básicos de unicidade e não nulidade.")
else:
    print(" Foram identificados possíveis problemas na chave.")

## 7. Análise de duplicidades

Registros duplicados podem indicar problemas na carga ou na integridade
dos dados.

Primeiramente será verificada a existência de linhas completamente
duplicadas.

In [54]:
# Quantidade de linhas completamente duplicadas.
quantidade_duplicados = df.duplicated().sum()

print("Registros duplicados:", quantidade_duplicados)

Registros duplicados: 0

In [ ]:
# Exibe os registros duplicados.
duplicados = df[df.duplicated(keep=False)]

duplicados